//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nurun.Data
{
    using Nurun.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Medicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicos()
        {
            this.RelHospitalMedico = new HashSet<RelHospitalMedico>();
        }
    
        public int idMedico { get; set; }
        [Required]
        public string Nombres { get; set; }
        [Required]
        public string Apellidos { get; set; }
        public string NombreCompleto { get { return string.Format("{0} {1}", Nombres, Apellidos); } }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        [Required]
        [Display(Name = "Hospital")]
        public int idHospital { get; set; }
        public string HospitalNombre { get; set; }
        public IEnumerable<SelectListItem> Hospitals { get; set; }
    
        public virtual Hospitales Hospitales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelHospitalMedico> RelHospitalMedico { get; set; }
    }

    public class MedicosDTO : Medicos { }
}
