//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nurun.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelHospitalMedico
    {
        public int idRelacionHospitalMedico { get; set; }
        public int idHospital { get; set; }
        public int idMedico { get; set; }
    
        public virtual Hospitales Hospitales { get; set; }
        public virtual Medicos Medicos { get; set; }
    }
}
